export const ttuClubs = [
    "Bergen Vest",
    "Bergstaden",
    "Brandbu",
    "Bjerke",
    "Bø",
    "Centrum",
    "Elverum",
    "Evje",
    "Florø",
    "Hamar",
    "I.R",
    "Islev",
    "Kunja",
    "Larvik",
    "Lillesand",
    "Lund",
    "Lyngby",
    "Meland",
    "Moss",
    "Munkholmen",
    "Nesodden",
    "Nittedal",
    "Nordfjord",
    "Notodden",
    "Oppsal",
    "OSI",
    "Osterøy",
    "Ringerike",
    "Ski Taekwondo Klubb",
    "Solør",
    "Steinkjer",
    "Sunnfjord",
    "Sædalen",
    "Tynset",
    "Ålesund",
    "Sølvbyen"
]